/**
 * This class is generated by jOOQ
 */
package de.blizzy.backup.database.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings("all")
public class BackupsRecord extends org.jooq.impl.UpdatableRecordImpl<de.blizzy.backup.database.schema.tables.records.BackupsRecord> {

	private static final long serialVersionUID = -1325064430;

	/**
	 * The table column <code>PUBLIC.BACKUPS.ID</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setId(java.lang.Integer value) {
		setValue(de.blizzy.backup.database.schema.tables.Backups.BACKUPS.ID, value);
	}

	/**
	 * The table column <code>PUBLIC.BACKUPS.ID</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.lang.Integer getId() {
		return getValue(de.blizzy.backup.database.schema.tables.Backups.BACKUPS.ID);
	}

	/**
	 * The table column <code>PUBLIC.BACKUPS.RUN_TIME</code>
	 */
	public void setRunTime(java.sql.Timestamp value) {
		setValue(de.blizzy.backup.database.schema.tables.Backups.BACKUPS.RUN_TIME, value);
	}

	/**
	 * The table column <code>PUBLIC.BACKUPS.RUN_TIME</code>
	 */
	public java.sql.Timestamp getRunTime() {
		return getValue(de.blizzy.backup.database.schema.tables.Backups.BACKUPS.RUN_TIME);
	}

	/**
	 * The table column <code>PUBLIC.BACKUPS.NUM_ENTRIES</code>
	 */
	public void setNumEntries(java.lang.Integer value) {
		setValue(de.blizzy.backup.database.schema.tables.Backups.BACKUPS.NUM_ENTRIES, value);
	}

	/**
	 * The table column <code>PUBLIC.BACKUPS.NUM_ENTRIES</code>
	 */
	public java.lang.Integer getNumEntries() {
		return getValue(de.blizzy.backup.database.schema.tables.Backups.BACKUPS.NUM_ENTRIES);
	}

	/**
	 * Create a detached BackupsRecord
	 */
	public BackupsRecord() {
		super(de.blizzy.backup.database.schema.tables.Backups.BACKUPS);
	}
}
