/**
 * This class is generated by jOOQ
 */
package de.blizzy.backup.database.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = "http://jooq.sourceforge.net",
                            comments = "This class is generated by jOOQ")
public class EntriesRecord extends org.jooq.impl.UpdatableRecordImpl<de.blizzy.backup.database.schema.tables.records.EntriesRecord> {

	private static final long serialVersionUID = -232843325;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setId(java.lang.Integer value) {
		setValue(de.blizzy.backup.database.schema.tables.Entries.ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.Integer getId() {
		return getValue(de.blizzy.backup.database.schema.tables.Entries.ID);
	}

	/**
	 * An uncommented item
	 */
	public void setParentId(java.lang.Integer value) {
		setValue(de.blizzy.backup.database.schema.tables.Entries.PARENT_ID, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getParentId() {
		return getValue(de.blizzy.backup.database.schema.tables.Entries.PARENT_ID);
	}

	/**
	 * An uncommented item
	 */
	public void setBackupId(java.lang.Integer value) {
		setValue(de.blizzy.backup.database.schema.tables.Entries.BACKUP_ID, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getBackupId() {
		return getValue(de.blizzy.backup.database.schema.tables.Entries.BACKUP_ID);
	}

	/**
	 * An uncommented item
	 */
	public void setType(java.lang.Byte value) {
		setValue(de.blizzy.backup.database.schema.tables.Entries.TYPE, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Byte getType() {
		return getValue(de.blizzy.backup.database.schema.tables.Entries.TYPE);
	}

	/**
	 * An uncommented item
	 */
	public void setCreationTime(java.sql.Timestamp value) {
		setValue(de.blizzy.backup.database.schema.tables.Entries.CREATION_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getCreationTime() {
		return getValue(de.blizzy.backup.database.schema.tables.Entries.CREATION_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setModificationTime(java.sql.Timestamp value) {
		setValue(de.blizzy.backup.database.schema.tables.Entries.MODIFICATION_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getModificationTime() {
		return getValue(de.blizzy.backup.database.schema.tables.Entries.MODIFICATION_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setHidden(java.lang.Boolean value) {
		setValue(de.blizzy.backup.database.schema.tables.Entries.HIDDEN, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Boolean getHidden() {
		return getValue(de.blizzy.backup.database.schema.tables.Entries.HIDDEN);
	}

	/**
	 * An uncommented item
	 */
	public void setName(java.lang.String value) {
		setValue(de.blizzy.backup.database.schema.tables.Entries.NAME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getName() {
		return getValue(de.blizzy.backup.database.schema.tables.Entries.NAME);
	}

	/**
	 * An uncommented item
	 */
	public void setFileId(java.lang.Integer value) {
		setValue(de.blizzy.backup.database.schema.tables.Entries.FILE_ID, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getFileId() {
		return getValue(de.blizzy.backup.database.schema.tables.Entries.FILE_ID);
	}

	/**
	 * Create a detached EntriesRecord
	 */
	public EntriesRecord() {
		super(de.blizzy.backup.database.schema.tables.Entries.ENTRIES);
	}

	/**
	 * Create an attached EntriesRecord
	 */
	public EntriesRecord(org.jooq.Configuration configuration) {
		super(de.blizzy.backup.database.schema.tables.Entries.ENTRIES, configuration);
	}
}
