/**
 * This class is generated by jOOQ
 */
package de.blizzy.backup.database.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
public class EntriesRecord extends org.jooq.impl.UpdatableRecordImpl<de.blizzy.backup.database.schema.tables.records.EntriesRecord> {

	private static final long serialVersionUID = 1861341810;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setId(java.lang.Integer value) {
		setValue(de.blizzy.backup.database.schema.tables.Entries.ENTRIES.ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.Integer getId() {
		return getValue(de.blizzy.backup.database.schema.tables.Entries.ENTRIES.ID);
	}

	/**
	 * An uncommented item
	 */
	public void setParentId(java.lang.Integer value) {
		setValue(de.blizzy.backup.database.schema.tables.Entries.ENTRIES.PARENT_ID, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getParentId() {
		return getValue(de.blizzy.backup.database.schema.tables.Entries.ENTRIES.PARENT_ID);
	}

	/**
	 * An uncommented item
	 */
	public void setBackupId(java.lang.Integer value) {
		setValue(de.blizzy.backup.database.schema.tables.Entries.ENTRIES.BACKUP_ID, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getBackupId() {
		return getValue(de.blizzy.backup.database.schema.tables.Entries.ENTRIES.BACKUP_ID);
	}

	/**
	 * An uncommented item
	 */
	public void setType(java.lang.Byte value) {
		setValue(de.blizzy.backup.database.schema.tables.Entries.ENTRIES.TYPE, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Byte getType() {
		return getValue(de.blizzy.backup.database.schema.tables.Entries.ENTRIES.TYPE);
	}

	/**
	 * An uncommented item
	 */
	public void setCreationTime(java.sql.Timestamp value) {
		setValue(de.blizzy.backup.database.schema.tables.Entries.ENTRIES.CREATION_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getCreationTime() {
		return getValue(de.blizzy.backup.database.schema.tables.Entries.ENTRIES.CREATION_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setModificationTime(java.sql.Timestamp value) {
		setValue(de.blizzy.backup.database.schema.tables.Entries.ENTRIES.MODIFICATION_TIME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.sql.Timestamp getModificationTime() {
		return getValue(de.blizzy.backup.database.schema.tables.Entries.ENTRIES.MODIFICATION_TIME);
	}

	/**
	 * An uncommented item
	 */
	public void setHidden(java.lang.Boolean value) {
		setValue(de.blizzy.backup.database.schema.tables.Entries.ENTRIES.HIDDEN, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Boolean getHidden() {
		return getValue(de.blizzy.backup.database.schema.tables.Entries.ENTRIES.HIDDEN);
	}

	/**
	 * An uncommented item
	 */
	public void setName(java.lang.String value) {
		setValue(de.blizzy.backup.database.schema.tables.Entries.ENTRIES.NAME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getName() {
		return getValue(de.blizzy.backup.database.schema.tables.Entries.ENTRIES.NAME);
	}

	/**
	 * An uncommented item
	 */
	public void setFileId(java.lang.Integer value) {
		setValue(de.blizzy.backup.database.schema.tables.Entries.ENTRIES.FILE_ID, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getFileId() {
		return getValue(de.blizzy.backup.database.schema.tables.Entries.ENTRIES.FILE_ID);
	}

	/**
	 * An uncommented item
	 */
	public void setNameLower(java.lang.String value) {
		setValue(de.blizzy.backup.database.schema.tables.Entries.ENTRIES.NAME_LOWER, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getNameLower() {
		return getValue(de.blizzy.backup.database.schema.tables.Entries.ENTRIES.NAME_LOWER);
	}

	/**
	 * Create a detached EntriesRecord
	 */
	public EntriesRecord() {
		super(de.blizzy.backup.database.schema.tables.Entries.ENTRIES);
	}
}
