/**
 * This class is generated by jOOQ
 */
package de.blizzy.backup.database.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
public class FilesRecord extends org.jooq.impl.UpdatableRecordImpl<de.blizzy.backup.database.schema.tables.records.FilesRecord> {

	private static final long serialVersionUID = 1146208825;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setId(java.lang.Integer value) {
		setValue(de.blizzy.backup.database.schema.tables.Files.FILES.ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.Integer getId() {
		return getValue(de.blizzy.backup.database.schema.tables.Files.FILES.ID);
	}

	/**
	 * An uncommented item
	 */
	public void setBackupPath(java.lang.String value) {
		setValue(de.blizzy.backup.database.schema.tables.Files.FILES.BACKUP_PATH, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getBackupPath() {
		return getValue(de.blizzy.backup.database.schema.tables.Files.FILES.BACKUP_PATH);
	}

	/**
	 * An uncommented item
	 */
	public void setChecksum(java.lang.String value) {
		setValue(de.blizzy.backup.database.schema.tables.Files.FILES.CHECKSUM, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getChecksum() {
		return getValue(de.blizzy.backup.database.schema.tables.Files.FILES.CHECKSUM);
	}

	/**
	 * An uncommented item
	 */
	public void setLength(java.lang.Long value) {
		setValue(de.blizzy.backup.database.schema.tables.Files.FILES.LENGTH, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Long getLength() {
		return getValue(de.blizzy.backup.database.schema.tables.Files.FILES.LENGTH);
	}

	/**
	 * An uncommented item
	 */
	public void setCompression(java.lang.Byte value) {
		setValue(de.blizzy.backup.database.schema.tables.Files.FILES.COMPRESSION, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Byte getCompression() {
		return getValue(de.blizzy.backup.database.schema.tables.Files.FILES.COMPRESSION);
	}

	/**
	 * Create a detached FilesRecord
	 */
	public FilesRecord() {
		super(de.blizzy.backup.database.schema.tables.Files.FILES);
	}
}
