/**
 * This class is generated by jOOQ
 */
package de.blizzy.backup.database.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = "http://jooq.sourceforge.net",
                            comments = "This class is generated by jOOQ")
public class FilesRecord extends org.jooq.impl.UpdatableRecordImpl<de.blizzy.backup.database.schema.tables.records.FilesRecord> {

	private static final long serialVersionUID = 2114226117;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setId(java.lang.Integer value) {
		setValue(de.blizzy.backup.database.schema.tables.Files.ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.Integer getId() {
		return getValue(de.blizzy.backup.database.schema.tables.Files.ID);
	}

	/**
	 * An uncommented item
	 */
	public void setBackupPath(java.lang.String value) {
		setValue(de.blizzy.backup.database.schema.tables.Files.BACKUP_PATH, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getBackupPath() {
		return getValue(de.blizzy.backup.database.schema.tables.Files.BACKUP_PATH);
	}

	/**
	 * An uncommented item
	 */
	public void setChecksum(java.lang.String value) {
		setValue(de.blizzy.backup.database.schema.tables.Files.CHECKSUM, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getChecksum() {
		return getValue(de.blizzy.backup.database.schema.tables.Files.CHECKSUM);
	}

	/**
	 * An uncommented item
	 */
	public void setLength(java.lang.Long value) {
		setValue(de.blizzy.backup.database.schema.tables.Files.LENGTH, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Long getLength() {
		return getValue(de.blizzy.backup.database.schema.tables.Files.LENGTH);
	}

	/**
	 * Create a detached FilesRecord
	 */
	public FilesRecord() {
		super(de.blizzy.backup.database.schema.tables.Files.FILES);
	}
}
