/**
 * This class is generated by jOOQ
 */
package de.blizzy.backup.database.schema;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the PUBLIC schema
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({"unchecked"})
public class Keys extends org.jooq.impl.AbstractKeys {

	// IDENTITY definitions
	public static final org.jooq.Identity<de.blizzy.backup.database.schema.tables.records.BackupsRecord, java.lang.Integer> IDENTITY_BACKUPS = createIdentity(de.blizzy.backup.database.schema.tables.Backups.BACKUPS, de.blizzy.backup.database.schema.tables.Backups.BACKUPS.ID);
	public static final org.jooq.Identity<de.blizzy.backup.database.schema.tables.records.EntriesRecord, java.lang.Integer> IDENTITY_ENTRIES = createIdentity(de.blizzy.backup.database.schema.tables.Entries.ENTRIES, de.blizzy.backup.database.schema.tables.Entries.ENTRIES.ID);
	public static final org.jooq.Identity<de.blizzy.backup.database.schema.tables.records.FilesRecord, java.lang.Integer> IDENTITY_FILES = createIdentity(de.blizzy.backup.database.schema.tables.Files.FILES, de.blizzy.backup.database.schema.tables.Files.FILES.ID);

	// UNIQUE and PRIMARY KEY definitions
	public static final org.jooq.UniqueKey<de.blizzy.backup.database.schema.tables.records.BackupsRecord> CONSTRAINT_1 = createUniqueKey(de.blizzy.backup.database.schema.tables.Backups.BACKUPS, de.blizzy.backup.database.schema.tables.Backups.BACKUPS.ID);
	public static final org.jooq.UniqueKey<de.blizzy.backup.database.schema.tables.records.EntriesRecord> CONSTRAINT_C = createUniqueKey(de.blizzy.backup.database.schema.tables.Entries.ENTRIES, de.blizzy.backup.database.schema.tables.Entries.ENTRIES.ID);
	public static final org.jooq.UniqueKey<de.blizzy.backup.database.schema.tables.records.FilesRecord> CONSTRAINT_3 = createUniqueKey(de.blizzy.backup.database.schema.tables.Files.FILES, de.blizzy.backup.database.schema.tables.Files.FILES.ID);

	// FOREIGN KEY definitions

	/**
	 * No instances
	 */
	private Keys() {}
}
