/**
 * This class is generated by jOOQ
 */
package de.blizzy.backup.database.schema;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = "http://jooq.sourceforge.net",
                            comments = "This class is generated by jOOQ")
@SuppressWarnings("nls")
public class Public extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1800493344;

	/**
	 * The singleton instance of PUBLIC
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * No further instances allowed
	 */
	private Public() {
		super("PUBLIC");
	}

	@Override
	public final java.util.List<org.jooq.Sequence> getSequences() {
		return java.util.Arrays.<org.jooq.Sequence>asList(
			de.blizzy.backup.database.schema.Sequences.SYSTEM_SEQUENCE_13ADACAB_9D86_4701_B832_9CC16F85CCE0,
			de.blizzy.backup.database.schema.Sequences.SYSTEM_SEQUENCE_1FD5204B_6224_49E3_8353_CE6CFD9A74B1,
			de.blizzy.backup.database.schema.Sequences.SYSTEM_SEQUENCE_A9688E17_7D84_4DFF_98DD_C4122372B13C);
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			de.blizzy.backup.database.schema.tables.Backups.BACKUPS,
			de.blizzy.backup.database.schema.tables.Files.FILES,
			de.blizzy.backup.database.schema.tables.Entries.ENTRIES);
	}
}
