/**
 * This class is generated by jOOQ
 */
package de.blizzy.backup.database.schema;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "1.6.8"},
                            comments = "This class is generated by jOOQ")
@SuppressWarnings("nls")
public class Public extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 1551878597;

	/**
	 * The singleton instance of PUBLIC
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * No further instances allowed
	 */
	private Public() {
		super("PUBLIC");
	}

	@Override
	public final java.util.List<org.jooq.Sequence> getSequences() {
		return java.util.Arrays.<org.jooq.Sequence>asList(
			de.blizzy.backup.database.schema.Sequences.SYSTEM_SEQUENCE_1F25903E_691F_4157_9F3C_3757E62B5DD4,
			de.blizzy.backup.database.schema.Sequences.SYSTEM_SEQUENCE_6F8C7182_BB0B_463B_BB4D_61D1EA6EE391,
			de.blizzy.backup.database.schema.Sequences.SYSTEM_SEQUENCE_C82CD0E0_44D2_4E99_8793_97CF93FD142F);
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			de.blizzy.backup.database.schema.tables.Backups.BACKUPS,
			de.blizzy.backup.database.schema.tables.Files.FILES,
			de.blizzy.backup.database.schema.tables.Entries.ENTRIES);
	}
}
