/**
 * This class is generated by jOOQ
 */
package de.blizzy.backup.database.schema;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all sequences in PUBLIC
 */
@javax.annotation.Generated(value    = "http://jooq.sourceforge.net",
                            comments = "This class is generated by jOOQ")
@SuppressWarnings("nls")
public final class Sequences {

	/**
	 * The sequence SYSTEM_SEQUENCE_13ADACAB_9D86_4701_B832_9CC16F85CCE0
	 */
	public static final org.jooq.Sequence SYSTEM_SEQUENCE_13ADACAB_9D86_4701_B832_9CC16F85CCE0 = new org.jooq.impl.SequenceImpl("SYSTEM_SEQUENCE_13ADACAB_9D86_4701_B832_9CC16F85CCE0", de.blizzy.backup.database.schema.Public.PUBLIC);

	/**
	 * The sequence SYSTEM_SEQUENCE_1FD5204B_6224_49E3_8353_CE6CFD9A74B1
	 */
	public static final org.jooq.Sequence SYSTEM_SEQUENCE_1FD5204B_6224_49E3_8353_CE6CFD9A74B1 = new org.jooq.impl.SequenceImpl("SYSTEM_SEQUENCE_1FD5204B_6224_49E3_8353_CE6CFD9A74B1", de.blizzy.backup.database.schema.Public.PUBLIC);

	/**
	 * The sequence SYSTEM_SEQUENCE_A9688E17_7D84_4DFF_98DD_C4122372B13C
	 */
	public static final org.jooq.Sequence SYSTEM_SEQUENCE_A9688E17_7D84_4DFF_98DD_C4122372B13C = new org.jooq.impl.SequenceImpl("SYSTEM_SEQUENCE_A9688E17_7D84_4DFF_98DD_C4122372B13C", de.blizzy.backup.database.schema.Public.PUBLIC);

	/**
	 * No instances
	 */
	private Sequences() {}
}
