/**
 * This class is generated by jOOQ
 */
package de.blizzy.backup.database.schema;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all sequences in PUBLIC
 */
@javax.annotation.Generated(value    = "http://jooq.sourceforge.net",
                            comments = "This class is generated by jOOQ")
public final class Sequences {

	/**
	 * The sequence SYSTEM_SEQUENCE_7793367E_B01B_413F_9E09_47F40E6347B8
	 */
	public static final org.jooq.Sequence SYSTEM_SEQUENCE_7793367E_B01B_413F_9E09_47F40E6347B8 = new org.jooq.impl.SequenceImpl("SYSTEM_SEQUENCE_7793367E_B01B_413F_9E09_47F40E6347B8", de.blizzy.backup.database.schema.Public.PUBLIC);

	/**
	 * The sequence SYSTEM_SEQUENCE_83357AAB_ECD6_4989_A03B_C5985DA4BFAB
	 */
	public static final org.jooq.Sequence SYSTEM_SEQUENCE_83357AAB_ECD6_4989_A03B_C5985DA4BFAB = new org.jooq.impl.SequenceImpl("SYSTEM_SEQUENCE_83357AAB_ECD6_4989_A03B_C5985DA4BFAB", de.blizzy.backup.database.schema.Public.PUBLIC);

	/**
	 * The sequence SYSTEM_SEQUENCE_E9EB531E_3071_444D_9DE6_DAE7B1F0E917
	 */
	public static final org.jooq.Sequence SYSTEM_SEQUENCE_E9EB531E_3071_444D_9DE6_DAE7B1F0E917 = new org.jooq.impl.SequenceImpl("SYSTEM_SEQUENCE_E9EB531E_3071_444D_9DE6_DAE7B1F0E917", de.blizzy.backup.database.schema.Public.PUBLIC);

	/**
	 * No instances
	 */
	private Sequences() {}
}
