/**
 * This class is generated by jOOQ
 */
package de.blizzy.backup.database.schema;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all sequences in PUBLIC
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "1.6.8"},
                            comments = "This class is generated by jOOQ")
@SuppressWarnings("nls")
public final class Sequences {

	/**
	 * The sequence SYSTEM_SEQUENCE_1F25903E_691F_4157_9F3C_3757E62B5DD4
	 */
	public static final org.jooq.Sequence SYSTEM_SEQUENCE_1F25903E_691F_4157_9F3C_3757E62B5DD4 = new org.jooq.impl.SequenceImpl("SYSTEM_SEQUENCE_1F25903E_691F_4157_9F3C_3757E62B5DD4", de.blizzy.backup.database.schema.Public.PUBLIC);

	/**
	 * The sequence SYSTEM_SEQUENCE_6F8C7182_BB0B_463B_BB4D_61D1EA6EE391
	 */
	public static final org.jooq.Sequence SYSTEM_SEQUENCE_6F8C7182_BB0B_463B_BB4D_61D1EA6EE391 = new org.jooq.impl.SequenceImpl("SYSTEM_SEQUENCE_6F8C7182_BB0B_463B_BB4D_61D1EA6EE391", de.blizzy.backup.database.schema.Public.PUBLIC);

	/**
	 * The sequence SYSTEM_SEQUENCE_C82CD0E0_44D2_4E99_8793_97CF93FD142F
	 */
	public static final org.jooq.Sequence SYSTEM_SEQUENCE_C82CD0E0_44D2_4E99_8793_97CF93FD142F = new org.jooq.impl.SequenceImpl("SYSTEM_SEQUENCE_C82CD0E0_44D2_4E99_8793_97CF93FD142F", de.blizzy.backup.database.schema.Public.PUBLIC);

	/**
	 * No instances
	 */
	private Sequences() {}
}
