/**
 * This class is generated by jOOQ
 */
package de.blizzy.backup.database.schema;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in PUBLIC
 */
public final class Tables {

	/**
	 * The table PUBLIC.BACKUPS
	 */
	public static de.blizzy.backup.database.schema.tables.Backups BACKUPS = de.blizzy.backup.database.schema.tables.Backups.BACKUPS;

	/**
	 * The table PUBLIC.ENTRIES
	 */
	public static de.blizzy.backup.database.schema.tables.Entries ENTRIES = de.blizzy.backup.database.schema.tables.Entries.ENTRIES;

	/**
	 * The table PUBLIC.FILES
	 */
	public static de.blizzy.backup.database.schema.tables.Files FILES = de.blizzy.backup.database.schema.tables.Files.FILES;

	/**
	 * No instances
	 */
	private Tables() {}
}
