/**
 * This class is generated by jOOQ
 */
package de.blizzy.backup.database.schema.tables;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings("nls")
public class Backups extends org.jooq.impl.UpdatableTableImpl<de.blizzy.backup.database.schema.tables.records.BackupsRecord> {

	private static final long serialVersionUID = -566468605;

	/**
	 * The singleton instance of PUBLIC.BACKUPS
	 */
	public static final de.blizzy.backup.database.schema.tables.Backups BACKUPS = new de.blizzy.backup.database.schema.tables.Backups();

	/**
	 * The class holding records for this type
	 */
	private static final java.lang.Class<de.blizzy.backup.database.schema.tables.records.BackupsRecord> __RECORD_TYPE = de.blizzy.backup.database.schema.tables.records.BackupsRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<de.blizzy.backup.database.schema.tables.records.BackupsRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public final org.jooq.TableField<de.blizzy.backup.database.schema.tables.records.BackupsRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<de.blizzy.backup.database.schema.tables.records.BackupsRecord, java.sql.Timestamp> RUN_TIME = createField("RUN_TIME", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<de.blizzy.backup.database.schema.tables.records.BackupsRecord, java.lang.Integer> NUM_ENTRIES = createField("NUM_ENTRIES", org.jooq.impl.SQLDataType.INTEGER, this);

	public Backups() {
		super("BACKUPS", de.blizzy.backup.database.schema.Public.PUBLIC);
	}

	public Backups(java.lang.String alias) {
		super(alias, de.blizzy.backup.database.schema.Public.PUBLIC, de.blizzy.backup.database.schema.tables.Backups.BACKUPS);
	}

	@Override
	public org.jooq.Identity<de.blizzy.backup.database.schema.tables.records.BackupsRecord, java.lang.Integer> getIdentity() {
		return de.blizzy.backup.database.schema.Keys.IDENTITY_BACKUPS;
	}

	@Override
	public org.jooq.UniqueKey<de.blizzy.backup.database.schema.tables.records.BackupsRecord> getMainKey() {
		return de.blizzy.backup.database.schema.Keys.CONSTRAINT_1;
	}

	@Override
	public java.util.List<org.jooq.UniqueKey<de.blizzy.backup.database.schema.tables.records.BackupsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<de.blizzy.backup.database.schema.tables.records.BackupsRecord>>asList(de.blizzy.backup.database.schema.Keys.CONSTRAINT_1);
	}

	@Override
	public de.blizzy.backup.database.schema.tables.Backups as(java.lang.String alias) {
		return new de.blizzy.backup.database.schema.tables.Backups(alias);
	}
}
