/**
 * This class is generated by jOOQ
 */
package de.blizzy.backup.database.schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "1.6.8"},
                            comments = "This class is generated by jOOQ")
@SuppressWarnings("nls")
public class Backups extends org.jooq.impl.UpdatableTableImpl<de.blizzy.backup.database.schema.tables.records.BackupsRecord> {

	private static final long serialVersionUID = -91378042;

	/**
	 * The singleton instance of BACKUPS
	 */
	public static final de.blizzy.backup.database.schema.tables.Backups BACKUPS = new de.blizzy.backup.database.schema.tables.Backups();

	/**
	 * The class holding records for this type
	 */
	private static final java.lang.Class<de.blizzy.backup.database.schema.tables.records.BackupsRecord> __RECORD_TYPE = de.blizzy.backup.database.schema.tables.records.BackupsRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<de.blizzy.backup.database.schema.tables.records.BackupsRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public static final org.jooq.TableField<de.blizzy.backup.database.schema.tables.records.BackupsRecord, java.lang.Integer> ID = new org.jooq.impl.TableFieldImpl<>("ID", org.jooq.impl.SQLDataType.INTEGER, BACKUPS);

	/**
	 * An uncommented item
	 */
	public static final org.jooq.TableField<de.blizzy.backup.database.schema.tables.records.BackupsRecord, java.sql.Timestamp> RUN_TIME = new org.jooq.impl.TableFieldImpl<>("RUN_TIME", org.jooq.impl.SQLDataType.TIMESTAMP, BACKUPS);

	/**
	 * An uncommented item
	 */
	public static final org.jooq.TableField<de.blizzy.backup.database.schema.tables.records.BackupsRecord, java.lang.Integer> NUM_ENTRIES = new org.jooq.impl.TableFieldImpl<>("NUM_ENTRIES", org.jooq.impl.SQLDataType.INTEGER, BACKUPS);

	/**
	 * No further instances allowed
	 */
	private Backups() {
		super("BACKUPS", de.blizzy.backup.database.schema.Public.PUBLIC);
	}

	@Override
	public org.jooq.Identity<de.blizzy.backup.database.schema.tables.records.BackupsRecord, java.lang.Integer> getIdentity() {
		return de.blizzy.backup.database.schema.Keys.IDENTITY_BACKUPS;
	}

	@Override
	public org.jooq.UniqueKey<de.blizzy.backup.database.schema.tables.records.BackupsRecord> getMainKey() {
		return de.blizzy.backup.database.schema.Keys.CONSTRAINT_1;
	}

	@Override
	public java.util.List<org.jooq.UniqueKey<de.blizzy.backup.database.schema.tables.records.BackupsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<de.blizzy.backup.database.schema.tables.records.BackupsRecord>>asList(de.blizzy.backup.database.schema.Keys.CONSTRAINT_1);
	}
}
