/**
 * This class is generated by jOOQ
 */
package de.blizzy.backup.database.schema.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings("all")
public class Entries extends org.jooq.impl.UpdatableTableImpl<de.blizzy.backup.database.schema.tables.records.EntriesRecord> {

	private static final long serialVersionUID = 45621598;

	/**
	 * The singleton instance of PUBLIC.ENTRIES
	 */
	public static final de.blizzy.backup.database.schema.tables.Entries ENTRIES = new de.blizzy.backup.database.schema.tables.Entries();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<de.blizzy.backup.database.schema.tables.records.EntriesRecord> getRecordType() {
		return de.blizzy.backup.database.schema.tables.records.EntriesRecord.class;
	}

	/**
	 * The table column <code>PUBLIC.ENTRIES.ID</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<de.blizzy.backup.database.schema.tables.records.EntriesRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>PUBLIC.ENTRIES.PARENT_ID</code>
	 */
	public final org.jooq.TableField<de.blizzy.backup.database.schema.tables.records.EntriesRecord, java.lang.Integer> PARENT_ID = createField("PARENT_ID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>PUBLIC.ENTRIES.BACKUP_ID</code>
	 */
	public final org.jooq.TableField<de.blizzy.backup.database.schema.tables.records.EntriesRecord, java.lang.Integer> BACKUP_ID = createField("BACKUP_ID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>PUBLIC.ENTRIES.TYPE</code>
	 */
	public final org.jooq.TableField<de.blizzy.backup.database.schema.tables.records.EntriesRecord, java.lang.Byte> TYPE = createField("TYPE", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * The table column <code>PUBLIC.ENTRIES.CREATION_TIME</code>
	 */
	public final org.jooq.TableField<de.blizzy.backup.database.schema.tables.records.EntriesRecord, java.sql.Timestamp> CREATION_TIME = createField("CREATION_TIME", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The table column <code>PUBLIC.ENTRIES.MODIFICATION_TIME</code>
	 */
	public final org.jooq.TableField<de.blizzy.backup.database.schema.tables.records.EntriesRecord, java.sql.Timestamp> MODIFICATION_TIME = createField("MODIFICATION_TIME", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The table column <code>PUBLIC.ENTRIES.HIDDEN</code>
	 */
	public final org.jooq.TableField<de.blizzy.backup.database.schema.tables.records.EntriesRecord, java.lang.Boolean> HIDDEN = createField("HIDDEN", org.jooq.impl.SQLDataType.BOOLEAN, this);

	/**
	 * The table column <code>PUBLIC.ENTRIES.NAME</code>
	 */
	public final org.jooq.TableField<de.blizzy.backup.database.schema.tables.records.EntriesRecord, java.lang.String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>PUBLIC.ENTRIES.FILE_ID</code>
	 */
	public final org.jooq.TableField<de.blizzy.backup.database.schema.tables.records.EntriesRecord, java.lang.Integer> FILE_ID = createField("FILE_ID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>PUBLIC.ENTRIES.NAME_LOWER</code>
	 */
	public final org.jooq.TableField<de.blizzy.backup.database.schema.tables.records.EntriesRecord, java.lang.String> NAME_LOWER = createField("NAME_LOWER", org.jooq.impl.SQLDataType.VARCHAR, this);

	public Entries() {
		super("ENTRIES", de.blizzy.backup.database.schema.Public.PUBLIC);
	}

	public Entries(java.lang.String alias) {
		super(alias, de.blizzy.backup.database.schema.Public.PUBLIC, de.blizzy.backup.database.schema.tables.Entries.ENTRIES);
	}

	@Override
	public org.jooq.Identity<de.blizzy.backup.database.schema.tables.records.EntriesRecord, java.lang.Integer> getIdentity() {
		return de.blizzy.backup.database.schema.Keys.IDENTITY_ENTRIES;
	}

	@Override
	public org.jooq.UniqueKey<de.blizzy.backup.database.schema.tables.records.EntriesRecord> getMainKey() {
		return de.blizzy.backup.database.schema.Keys.CONSTRAINT_C;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<de.blizzy.backup.database.schema.tables.records.EntriesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<de.blizzy.backup.database.schema.tables.records.EntriesRecord>>asList(de.blizzy.backup.database.schema.Keys.CONSTRAINT_C);
	}

	@Override
	public de.blizzy.backup.database.schema.tables.Entries as(java.lang.String alias) {
		return new de.blizzy.backup.database.schema.tables.Entries(alias);
	}
}
