/**
 * This class is generated by jOOQ
 */
package de.blizzy.backup.database.schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.0.0"},
                            comments = "This class is generated by jOOQ")
@SuppressWarnings("nls")
public class Files extends org.jooq.impl.UpdatableTableImpl<de.blizzy.backup.database.schema.tables.records.FilesRecord> {

	private static final long serialVersionUID = -1856462659;

	/**
	 * The singleton instance of FILES
	 */
	public static final de.blizzy.backup.database.schema.tables.Files FILES = new de.blizzy.backup.database.schema.tables.Files();

	/**
	 * The class holding records for this type
	 */
	private static final java.lang.Class<de.blizzy.backup.database.schema.tables.records.FilesRecord> __RECORD_TYPE = de.blizzy.backup.database.schema.tables.records.FilesRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<de.blizzy.backup.database.schema.tables.records.FilesRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public final org.jooq.TableField<de.blizzy.backup.database.schema.tables.records.FilesRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<de.blizzy.backup.database.schema.tables.records.FilesRecord, java.lang.String> BACKUP_PATH = createField("BACKUP_PATH", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<de.blizzy.backup.database.schema.tables.records.FilesRecord, java.lang.String> CHECKSUM = createField("CHECKSUM", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<de.blizzy.backup.database.schema.tables.records.FilesRecord, java.lang.Long> LENGTH = createField("LENGTH", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<de.blizzy.backup.database.schema.tables.records.FilesRecord, java.lang.Byte> COMPRESSION = createField("COMPRESSION", org.jooq.impl.SQLDataType.TINYINT, this);

	/**
	 * No further instances allowed
	 */
	private Files() {
		super("FILES", de.blizzy.backup.database.schema.Public.PUBLIC);
	}

	/**
	 * No further instances allowed
	 */
	private Files(java.lang.String alias) {
		super(alias, de.blizzy.backup.database.schema.Public.PUBLIC, de.blizzy.backup.database.schema.tables.Files.FILES);
	}

	@Override
	public org.jooq.Identity<de.blizzy.backup.database.schema.tables.records.FilesRecord, java.lang.Integer> getIdentity() {
		return de.blizzy.backup.database.schema.Keys.IDENTITY_FILES;
	}

	@Override
	public org.jooq.UniqueKey<de.blizzy.backup.database.schema.tables.records.FilesRecord> getMainKey() {
		return de.blizzy.backup.database.schema.Keys.CONSTRAINT_3;
	}

	@Override
	public java.util.List<org.jooq.UniqueKey<de.blizzy.backup.database.schema.tables.records.FilesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<de.blizzy.backup.database.schema.tables.records.FilesRecord>>asList(de.blizzy.backup.database.schema.Keys.CONSTRAINT_3);
	}

	@Override
	public de.blizzy.backup.database.schema.tables.Files as(java.lang.String alias) {
		return new de.blizzy.backup.database.schema.tables.Files(alias);
	}
}
