/**
 * This class is generated by jOOQ
 */
package de.blizzy.backup.database.schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = "http://jooq.sourceforge.net",
                            comments = "This class is generated by jOOQ")
public class Files extends org.jooq.impl.UpdatableTableImpl<de.blizzy.backup.database.schema.tables.records.FilesRecord> {

	private static final long serialVersionUID = -51882157;

	/**
	 * The singleton instance of FILES
	 */
	public static final de.blizzy.backup.database.schema.tables.Files FILES = new de.blizzy.backup.database.schema.tables.Files();

	/**
	 * The class holding records for this type
	 */
	private static final java.lang.Class<de.blizzy.backup.database.schema.tables.records.FilesRecord> __RECORD_TYPE = de.blizzy.backup.database.schema.tables.records.FilesRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<de.blizzy.backup.database.schema.tables.records.FilesRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public static final org.jooq.TableField<de.blizzy.backup.database.schema.tables.records.FilesRecord, java.lang.Integer> ID = new org.jooq.impl.TableFieldImpl<de.blizzy.backup.database.schema.tables.records.FilesRecord, java.lang.Integer>("ID", org.jooq.impl.SQLDataType.INTEGER, FILES);

	/**
	 * An uncommented item
	 */
	public static final org.jooq.TableField<de.blizzy.backup.database.schema.tables.records.FilesRecord, java.lang.String> BACKUP_PATH = new org.jooq.impl.TableFieldImpl<de.blizzy.backup.database.schema.tables.records.FilesRecord, java.lang.String>("BACKUP_PATH", org.jooq.impl.SQLDataType.VARCHAR, FILES);

	/**
	 * An uncommented item
	 */
	public static final org.jooq.TableField<de.blizzy.backup.database.schema.tables.records.FilesRecord, java.lang.String> CHECKSUM = new org.jooq.impl.TableFieldImpl<de.blizzy.backup.database.schema.tables.records.FilesRecord, java.lang.String>("CHECKSUM", org.jooq.impl.SQLDataType.VARCHAR, FILES);

	/**
	 * An uncommented item
	 */
	public static final org.jooq.TableField<de.blizzy.backup.database.schema.tables.records.FilesRecord, java.lang.Long> LENGTH = new org.jooq.impl.TableFieldImpl<de.blizzy.backup.database.schema.tables.records.FilesRecord, java.lang.Long>("LENGTH", org.jooq.impl.SQLDataType.BIGINT, FILES);

	/**
	 * No further instances allowed
	 */
	private Files() {
		super("FILES", de.blizzy.backup.database.schema.Public.PUBLIC);
	}

	@Override
	public org.jooq.Identity<de.blizzy.backup.database.schema.tables.records.FilesRecord, java.lang.Integer> getIdentity() {
		return de.blizzy.backup.database.schema.Keys.IDENTITY_FILES;
	}

	@Override
	public org.jooq.UniqueKey<de.blizzy.backup.database.schema.tables.records.FilesRecord> getMainKey() {
		return de.blizzy.backup.database.schema.Keys.CONSTRAINT_3;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<de.blizzy.backup.database.schema.tables.records.FilesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<de.blizzy.backup.database.schema.tables.records.FilesRecord>>asList(de.blizzy.backup.database.schema.Keys.CONSTRAINT_3);
	}
}
